### ISSUE TITLE
admin message

### ISSUE THREAD

**Issue by davmak** [jeroenvermeulen/jeroenvermeulen-blockcache#1]
ERROR:
This extension requires cache backend: JeroenVermeulen_Cm_Cache_Backend_Redis
Current setting: Cm_Cache_Backend_Redis

If you would install 'Cm_Cache_Backend_File' you could also use 'JeroenVermeulen_Cm_Cache_Backend_File'.

I have colinmollenhour/Cm_Cache_Backend_Redis.

Any idea ?

**Comment by jeroenvermeulen** [comment]
Hi davmak,

I have written an install manual:
https://github.com/jeroenvermeulen/jeroenvermeulen-blockcache/wiki/Installation-Manual

Good luck!
