### ISSUE TITLE
admin message :: MageHost_Cm_Cache_Backend_Redis

### ISSUE THREAD

**Issue by hans2103** [jeroenvermeulen/jeroenvermeulen-blockcache#2]
after update your extension I get the following message:

> ERROR:
This extension requires cache backend: 'MageHost_Cm_Cache_Backend_Redis'
Current setting: 'File'

> If you would install 'Cm_Cache_Backend_File' you could also use 'MageHost_Cm_Cache_Backend_File'.

**Comment by jeroenvermeulen** [comment]
Hi Hans,

This is a normal error.
You need to edit your `app/etc/local.xml` and change the following:
```
<config>
    <global>
        ...
        <cache>
            <backend>MageHost_Cm_Cache_Backend_File</backend>
        </cache>
        ....
    </global>
</config>
```

**Comment by jeroenvermeulen** [comment]
I have also updated [the manual](https://github.com/jeroenvermeulen/jeroenvermeulen-blockcache/wiki/Installation-Manual)
